# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 田月阁
email: hyz725+github@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  自然语言处理 机器翻译
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xlhdh.github.io/" # the base hostname & protocol for your site
github_username:  xlhdh

# Build settings
markdown: kramdown

# Google services
google_analytics: UA-48926715-1

